#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 17 19:32:36 2017

@author: cspit
"""

entry = [['buy', 'SNAP', 10, 15.25, '2017-09-17 19:32:01', -152.5],
 [['sell', 'AAPL', 20, 159.88, '2017-09-17 19:32:05', -3197.6]]]
for i in range(len(entry)):
    x=[item for item in entry if entry[i][0]=='sell']
        