#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 17 14:23:35 2017

@author: cspit
"""
import datetime
from bs4 import BeautifulSoup
import urllib
trades = []
equities = ['AAPL', 'AMZN', 'MSFT', 'INTC', 'SNAP']


def mainscreen():
    print('1. Trade')
    print('2. Show Blotter')
    print('3. Show P/L')
    print('4. Quit')
    print('Please select an option')

done = False
while not done:
    mainscreen()
    option = int(input())
    if option==4:
        done=True
        print('Thank you for trading with us!')
    if option>4:
        print('Incorrect Option, please select from 1 to 4')
    if option==1:
        trade()
        done=True
    if option==2:
        show_blotter()
        done=True
    if option==3:
        show_pl()
        done=True        

def show_blotter():
    print("this is your current blotter")
    print("| Side   | Ticker   | Qty    | Pri | D/T             |")
    for item in trades:
        print("|",item[0]," "*(5-len(item[0])),"|",
              item[1]," "*(7-len(str(item[1]))),"|",
              item[2]," "*(4-len(str(item[2]))),"|",
              item[3]," "*(2-len(str(item[3]))),"|",
              item[4]," "*(2-len(str(item[4]))),"|")
        mainscreen()

def trade():
    print('Equities available')
    print('What would you like to do?')
    print('1. Sell')
    print('2. Buy')
    print('3. Return to Main')

done = False
while not done:
    option = int(input())
    if option==1:
        sell()
    if option==2:
        buy()
    if option==3:
        mainscreen()

def sell():
    print(equities)
    print('Which one would you like to sell?')

def buy():
    print(equities)
    print('Which one would you like to buy?')